/**** Código das visualizações criadas para a análise de dados./Code of visualizations created for data analysis. ****/

USE [olist]
GO

/****** Object:  View [dbo].[VW_PEDIDOS_POR_CLIENTES]    Script Date: 03/06/2022 12:40:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_PEDIDOS_POR_CLIENTES]
AS 

SELECT TOP 1000 O.*, C.CUSTOMER_CITY, C. CUSTOMER_STATE 
FROM [dbo].[TB_ACT_OLIST_ORDERS] AS O
INNER JOIN [dbo].[TB_ACT_OLIST_CUSTOMERS] AS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE ORDER_STATUS = 'delivered'
ORDER BY ORDER_ID ASC
GO


USE [olist]
GO

/****** Object:  View [dbo].[VW_ITENS_CLIENTE_ESTADO]    Script Date: 03/06/2022 12:41:01 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_ITENS_CLIENTE_ESTADO]
AS

SELECT TOP 1000 ITENS. *, CLIENTES.CUSTOMER_ID, ESTADO.CUSTOMER_STATE
FROM (([dbo].[TB_ACT_OLIST_ORDER_ITEMS] AS ITENS
INNER JOIN [dbo].[TB_ACT_OLIST_ORDERS] AS CLIENTES ON ITENS.ORDER_ID = CLIENTES.ORDER_ID)
INNER JOIN [dbo].[TB_ACT_OLIST_CUSTOMERS] AS ESTADO ON CLIENTES.CUSTOMER_ID = ESTADO.CUSTOMER_ID)

order by ORDER_ID asc
GO

USE [olist]
GO

/****** Object:  View [dbo].[VW_ITENS_CLIENTE]    Script Date: 03/06/2022 12:41:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_ITENS_CLIENTE]
AS

SELECT TOP 1000 ITENS. *, CLIENTES.CUSTOMER_ID
FROM [dbo].[TB_ACT_OLIST_ORDER_ITEMS] AS ITENS
INNER JOIN [dbo].[TB_ACT_OLIST_ORDERS] AS CLIENTES
ON ITENS.ORDER_ID = CLIENTES.ORDER_ID
order by ORDER_ID asc
GO

USE [olist]
GO

/****** Object:  View [dbo].[VW_CATEGORIA_PRODUTOS]    Script Date: 03/06/2022 12:41:54 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[VW_CATEGORIA_PRODUTOS]
AS

SELECT TOP 1000 PEDIDOS. *, CATEGORIA.PRODUCT_CATEGORY_NAME  
FROM (([dbo].[TB_ACT_OLIST_ORDER_ITEMS] AS PEDIDOS
INNER JOIN [dbo].[TB_ACT_OLIST_PRODUCTS] AS PRODUTOS ON PEDIDOS.PRODUCT_ID = PRODUTOS.PRODUCT_ID)
INNER JOIN [dbo].[TB_ACT_OLIST_PRODUCT_CATEGORY] AS CATEGORIA ON PRODUTOS.PRODUCT_CATEGORY_NAME = CATEGORIA.PRODUCT_CATEGORY_NAME)
ORDER BY ORDER_ID ASC
GO

